//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Brand
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Brand()
    {
        this.Products = new HashSet<Product>();
    }

    public int Id { get; set; }
    public string Title { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
}

public partial class Category
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Category()
    {
        this.Products = new HashSet<Product>();
    }

    public int Id { get; set; }
    public string Title { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
}

public partial class Company
{
    public int Id { get; set; }
    public Nullable<int> ServiceCharge { get; set; }
    public Nullable<int> PriceVat { get; set; }
}

public partial class Customer
{
    public int Id { get; set; }
    public string CustomerName { get; set; }
    public string CustomerPhone { get; set; }
    public string CustomerAddress { get; set; }
    public Nullable<System.DateTime> CustomerDOB { get; set; }
}

public partial class Order
{
    public int Id { get; set; }
    public Nullable<System.DateTime> OrderDate { get; set; }
    public string CustomerName { get; set; }
    public string CustomerPhone { get; set; }
    public string CustomerAddress { get; set; }
    public Nullable<System.DateTime> CustomerDOB { get; set; }
    public string ProductName { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<decimal> Rate { get; set; }
    public Nullable<decimal> Amount { get; set; }
    public Nullable<int> Vat { get; set; }
    public Nullable<int> ServiceCharge { get; set; }
    public Nullable<int> Discount { get; set; }
    public Nullable<decimal> NetAmount { get; set; }
}

public partial class Product
{
    public int Id { get; set; }
    public string ProductName { get; set; }
    public string ProductDescription { get; set; }
    public Nullable<decimal> ProductPrice { get; set; }
    public Nullable<int> ProductPriceTax { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<int> BrandId { get; set; }
    public string Brand { get; set; }
    public Nullable<int> SupplierId { get; set; }
    public string Supplier { get; set; }
    public Nullable<int> SizeId { get; set; }
    public string Size { get; set; }
    public Nullable<int> CategoryId { get; set; }
    public string Category { get; set; }
    public string ProductPhoto { get; set; }
    public string Status { get; set; }
    public Nullable<int> StoreId { get; set; }
    public string StoreName { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<decimal> TotalPrice { get; set; }

    public virtual Brand Brand1 { get; set; }
    public virtual Category Category1 { get; set; }
    public virtual Supplier Supplier1 { get; set; }
    public virtual Size Size1 { get; set; }
    public virtual Store Store { get; set; }
}

public partial class Size
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Size()
    {
        this.Products = new HashSet<Product>();
    }

    public int Id { get; set; }
    public string Title { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
}

public partial class Store
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Store()
    {
        this.Products = new HashSet<Product>();
    }

    public int Id { get; set; }
    public string StoreName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
}

public partial class Supplier
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Supplier()
    {
        this.Products = new HashSet<Product>();
    }

    public int Id { get; set; }
    public string SupplierName { get; set; }
    public string SupplierPhone { get; set; }
    public string SupplierAddress { get; set; }
    public string SupplierProduct { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
}

public partial class UserAccount
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public string Status { get; set; }
    public string Type { get; set; }
    public Nullable<int> TypeId { get; set; }
    public string Photo { get; set; }

    public virtual UserType UserType { get; set; }
}

public partial class UserType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserType()
    {
        this.UserAccounts = new HashSet<UserAccount>();
    }

    public int Id { get; set; }
    public string Type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UserAccount> UserAccounts { get; set; }
}
